#################
# Create a new pod called custom-nginx using the nginx image and expose it on container port 8080
# k run custom-nginx --image nginx --dry-run=client -o yaml > custom-nginx.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-nginx
  name: custom-nginx
spec:
  containers:
  - image: nginx
    name: custom-nginx
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}