apiVersion: v1
kind: Pod
metadata:
  name: nginx-rs
  creationTimestamp: null
  labels:
    env: prod
    tier: frontend
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
