apiVersion: v1
kind: Pod 
metadata: 
  name: dns-test-service-client-pod-prod
spec:
  containers:
  - name: curl
    image: appropriate/curl
    command: ["/bin/sh"]
    args: ["-c","curl dev.test-service:4000 "]
