apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec: 
  containers:
    - name: my-frontend
      image: nginx
      volumeMounts: 
      - mountPath: "/var/www/html"
        name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mypvcclaim


