apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /data
    type: Directory



