apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  selector:
    matchLabels:
      type: test
  storageClass: ""
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi  
  persistentVolumeReclaimPolicy: Delete
