---
# Let's fix that. Create a new PersistentVolumeClaim by the name of local-pvc that should bind to the volume local-pv.
# Inspect the pv local-pv for the specs.
# PVC: local-pvc
# Correct Access Mode?
# Correct StorageClass Used?
# PVC requests volume size = 500Mi?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi
---
# Create a new pod called nginx with the image nginx:alpine. The Pod should make use of the PVC local-pvc and mount the volume at the path /var/www/html.
# The PV local-pv should in a bound state.
# Pod created with the correct Image?
# Pod uses PVC called local-pvc?
# local-pv bound?
# nginx pod running?
# Volume mounted at the correct path?
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec: 
  containers:
    - name: nginx 
      image: nginx:alpine
      volumeMounts:
      - mountPath: "/var/www/html"
        name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: local-pvc
---
# Create a new Storage Class called delayed-volume-sc that makes use of the below specs:
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

# Storage Class uses: kubernetes.io/no-provisioner ?
# Storage Class volumeBindingMode set to WaitForFirstConsumer ?
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


