apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep"] ### Similar to Docker's ENTRYPOINT ["sleep"]
      args: ["10"] ### Similar to Docker's CMD ["10"]



