apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers: 
  - name: nginx-server
    image: nginx:latest
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: uhn7.local

                
apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl:7.76.1
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: uhn7.local

k set pod node-selector-pod nodeSelector.kubernetes.io/hostname=uhn7.local