apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers: 
  - name: nginx-server
    image: nginx:latest
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In 
                values: 
                - minikube